# This is a basic workflow to help you get started with Actions

name: Second GHA Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, Second GHA world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Run a Third Step in a single job multi step workflow
        run: |
          echo I am first echo of third step
          echo I am second line of third step of single job workflow
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: First step of linting
        run: echo Linting First step is here
      - name: Second step of linting
        run: echo Linting second step is here
      - name: Third step of linting
        run: |
          echo I am third step of lint job
          echo I am third step 2 of lint job
